/*
    Copyright (c) 2013 Yaniv Kamay,
    All rights reserved.

    Source code is provided for evaluation purposes only. Modification or use in
    source code for any other purpose is prohibited.

    Binary code (i.e. the binary form of source code form) is allowed to use for
    evaluation purposes only. Modification or use in binary code for any other
    purpose is prohibited.

    Redistribution, in source form or in binary form, with or without modification,
    are not permitted.

    THIS SOFTWARE IS PROVIDED BY THE COPYRIGHT HOLDERS AND CONTRIBUTORS "AS IS" AND
    ANY EXPRESS OR IMPLIED WARRANTIES, INCLUDING, BUT NOT LIMITED TO, THE IMPLIED
    WARRANTIES OF MERCHANTABILITY AND FITNESS FOR A PARTICULAR PURPOSE ARE
    DISCLAIMED. IN NO EVENT SHALL THE COPYRIGHT OWNER OR CONTRIBUTOR BE LIABLE FOR
    ANY DIRECT, INDIRECT, INCIDENTAL, SPECIAL, EXEMPLARY, OR CONSEQUENTIAL DAMAGES
    (INCLUDING, BUT NOT LIMITED TO, PROCUREMENT OF SUBSTITUTE GOODS OR SERVICES;
    LOSS OF USE, DATA, OR PROFITS; OR BUSINESS INTERRUPTION) HOWEVER CAUSED AND ON
    ANY THEORY OF LIABILITY, WHETHER IN CONTRACT, STRICT LIABILITY, OR TORT (INCLUDING
    NEGLIGENCE OR OTHERWISE) ARISING IN ANY WAY OUT OF THE USE OF THIS SOFTWARE, EVEN
    IF ADVISED OF THE POSSIBILITY OF SUCH DAMAGE.
*/

#ifndef _H_ERROR_CODES
#define _H_ERROR_CODES


enum {
    BIOS_ERROR_INVALID_PLATFORM_ARGS = 1,
    BIOS_ERROR_UNEXPECTED_IP,
    BIOS_ERROR_DOUBLE_HARD_INT,
    BIOS_ERROR_STI_WHILE_IN_IRQ_CONTEXT,
    BIOS_ERROR_OUT_OF_ROUTING_SLOTS,
    BIOS_ERROR_NO_VGA_EXP_ROM,
    BIOS_ERROR_EXP_ROM_NEW_SIZE,
    BIOS_ERROR_ATA_DIAGNOSTIC_FAILED,
    BIOS_ERROR_ATA_MALFUNCTION,
    BIOS_ERROR_ATA_INVALID_SIGNATURE,
    BIOS_ERROR_ATA_ID_FAILED,
    BIOS_ERROR_ATA_TYPE_MISMATCH,
    BISO_ERROR_REGISTER_INT_FAILED,
    BISO_ERROR_UNREGISTER_INT_FAILED,
    BIOS_ERROR_BOOT_INVALID_TYPE,
    BIOS_ERROR_PCI_INVALID_INTERRUPT_PIN,
    BIOS_ERROR_PCI_NO_IRQ_MASK,
    BIOS_ERROR_PCI_CONFIG_IRQ_FAILED,
};


enum {
    BIOS_WARN_KBD_WRITE_BLOCKED = 1,
    BIOS_WARN_ATA_RESET_TIMEOUT,
    BIOS_WARN_ATA_OUT_OF_SLOT,
    BIOS_WARN_BOOT_OUT_OF_SLOTS,
    BIOS_WARN_ATA_RESET_FAILED,
};


enum {
    BIOS_INFO_KBD_INT_MOUSE_DATA = 1,
    BIOS_INFO_MOUSE_INT_KBD_DATA,
};


#endif

